version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-nginx
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
