version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-nginx
    ports:
      - "8081:80" # Changed port to avoid conflict
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wordpress
    mem_limit: 64m # Reduced memory usage

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlPass
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3308:3306" # Changed port to avoid conflict
    mem_limit: 128m
    command: --innodb-buffer-pool-size=64M --innodb-log-file-size=32M

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mysqlPass
    ports:
      - "8082:80" # Changed port to avoid conflict
    mem_limit: 64m # Reduced memory usage

  wordpress:
    image: wordpress:php8.1-fpm
    container_name: wordpress
    depends_on:
      - db
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - ./html:/var/www/html
    # Removed ports section - PHP-FPM communicates internally
    mem_limit: 128m
